### ISSUE TITLE
How to create 3D MVP landing page with three.js?

### ISSUE THREAD

**Issue by webcat359** [narakarax/portfolio_blog#1]
As I'm a fresh web developer, I'd like to make Portfolio website.

If you know about this method, let me know about tools and framework.

**Comment by talented0312** [comment]
Thanks for your questions.

According to my opinion, I have made 3D website with Three.js fiber/drei and React-typeScript.

To build this, you have to know about 3D environment and 3D coordinate.

Also, you have good eye about design.

thanks

**Comment by webcat359** [comment]
let me know more details.

**Comment by talented0312** [comment]
- React-redux, State, Lifecycle
- Material Mapping (three.js)
